{
  "app": {
    "es": {
      "es_host": "http://localhost:9209",
      "index" : {
          "alias" : "metrics_search"
      }
    },
    "kafka": {
      "host": "localhost:29092,localhost:39092",
      "topic" : "test-topic,test1-topic"
    }
  }
}