{
  "app": {
    "es": {
      "es_host": "http://localhost:9203",
      "index" : {
          "alias" : "metrics_search",
          "index" : "fastapi_kafka_indexing"
      }
    },
    "kafka": {
      "host": "localhost:29092,localhost:39092",
      "topic" : "test-topic,test1-topic"
    },
    "logstash": {
      "host": "127.0.0.1",
      "port" : 5959
    }
  }
}
